# Generated by Django 3.1.5 on 2021-02-01 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='baso_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Basophils (% of White Blood Cells)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99.0)], verbose_name='BASO (% WBC)'),
        ),
        migrations.AddField(
            model_name='data',
            name='eo_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Eosinophils (% of White Blood Cells)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99.0)], verbose_name='EO (% WBC)'),
        ),
        migrations.AddField(
            model_name='data',
            name='lymp_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lymphocytes (% of White Blood Cells)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(99.0)], verbose_name='LYMPH (% WBC)'),
        ),
        migrations.AddField(
            model_name='data',
            name='mono_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monocytes (% of White Blood Cells)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(99.0)], verbose_name='MONO (% WBC)'),
        ),
        migrations.AddField(
            model_name='data',
            name='neut_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Neutrophils (% of White Blood Cells)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(99.0)], verbose_name='NEUT (% WBC)'),
        ),
    ]
