# Generated by Django 3.1.5 on 2021-03-03 05:38

from django.db import migrations


def enable_cift_in_examples(apps, schema_editor):
    SVC = apps.get_model("supervised_learning", "SVC")
    example_svcs = SVC.objects.filter(name__icontains="(Example)")
    for svc in example_svcs:
        svc.cift_is_enabled = True
        svc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_example_data'),
        ('ai_base', '0002_learningtechnique_cift_is_enabled'),
    ]

    operations = [
        migrations.RunPython(
            enable_cift_in_examples,
            migrations.RunPython.noop
        )
    ]
