# Generated by Django 3.1.5 on 2021-03-03 05:38

from django.db import migrations


def enable_introspection_in_examples(apps, schema_editor):
    SLT = apps.get_model("supervised_learning", "SupervisedLearningTechnique")
    example_slts = SLT.objects.filter(name__icontains="(Example)")
    for slt in example_slts:
        slt.data_imputer = \
            'django_ai.supervised_learning.models.IntrospectionImputer'
        slt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_example_data_enable_cift'),
        ('supervised_learning', '0009_hgbtreeimputer'),
    ]

    operations = [
        migrations.RunPython(
            enable_introspection_in_examples,
            migrations.RunPython.noop
        )
    ]
