# Generated by Django 3.1.5 on 2021-03-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_example_data_enable_introspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='is_finished',
            field=models.BooleanField(default=False, help_text='Is the record finished or complete? All data has been recorded and the internal identifier has been removed.', verbose_name='Is Finished?'),
        ),
    ]
