# Generated by Django 3.1.5 on 2021-03-22 21:36

from django.db import migrations


def mark_example_data_as_finished(apps, schema_editor):
    Data = apps.get_model("data", "Data")
    data = Data.objects.filter(unit__name__icontains="(E)")
    for d in data:
        d.is_finished = True
    Data.objects.bulk_update(data, ['is_finished'])


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_data_is_finished'),
    ]

    operations = [
        migrations.RunPython(
            mark_example_data_as_finished,
            migrations.RunPython.noop
        )
    ]
