# Generated by Django 3.1.5 on 2021-03-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_data_chtuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='is_covid19',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is COVID19?'),
        ),
    ]
