# Generated by Django 3.1.5 on 2021-04-12 23:06

from django.db import migrations


def generate_auth_token(apps, schema_editor):
    # Generate auth token for user 'staff' in order to do load testing
    # out-of-the-box
    User = apps.get_model("base", "User")
    Token = apps.get_model("authtoken", "Token")
    try:
        staff = User.objects.get(username='staff')
        Token.objects.create(user=staff, key="TheQuickBrownFox...")
    except Exception:
        print("Example Data not available or token already created - skipping")


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_example_data_fix'),
    ]

    operations = [
        migrations.RunPython(
            generate_auth_token,
            migrations.RunPython.noop
        )
    ]
