# Generated by Django 3.1.5 on 2021-05-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_example_data_auth_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='mnl_Upercentace_Rwbc',
            new_name='mnl_Upercentage_Rwbc',
        ),
    ]
