# Generated by Django 3.1.5 on 2021-05-13 00:37
import numpy as np
import random
import sys

from django.conf import settings
from django.core.management import call_command
from django.db import migrations

random.seed(123456)
np.random.seed(123456)


def create_example_data_v2(apps, schema_editor):
    call_command('example_data', '--create')


def remove_example_data_v2(apps, schema_editor):
    call_command('example_data', '--remove')


if getattr(settings, 'EXAMPLE_DATA_V2', False) and 'test' not in sys.argv:
    ops = [
        migrations.RunPython(
            create_example_data_v2,
            remove_example_data_v2
        )
    ]
else:
    ops = [
        migrations.RunPython(
            migrations.RunPython.noop,
            migrations.RunPython.noop,
        )
    ]
    print("EXAMPLE_DATA_V2 disabled")


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_data_rename_mnl_Upercentace_Rwbc'),
    ]

    operations = ops
