# Generated by Django 3.1.5 on 2021-02-06 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervised_learning', '0001_initial'),
        ('base', '0002_currentclassifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalClassifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('classifier_url', models.URLField(default='http://localhost/api/v1/classify', verbose_name='Classifier URL')),
                ('timeout', models.DecimalField(decimal_places=2, default=10, help_text='Seconds to wait for a response from the service', max_digits=5, verbose_name='Request Timeout (s)')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Extenal Classifier',
                'verbose_name_plural': 'Extenal Classifiers',
            },
        ),
        # migrations.AlterField(
        #     model_name='currentclassifier',
        #     name='classifier',
        #     field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_classifier', to='supervised_learning.hgbtree'),
        # ),
        migrations.AddField(
            model_name='currentclassifier',
            name='external',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_classifier', to='base.externalclassifier'),
        ),
    ]
