# Generated by Django 3.1.5 on 2021-03-09 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('base', '0005_decisiontree_svm'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('node_url', models.URLField(default='http://localhost', verbose_name="Network Node's URL")),
                ('endpoint_data', models.CharField(default='/api/v1/data', max_length=100, verbose_name='Endpoint for Data')),
                ('endpoint_classify', models.CharField(default='/api/v1/classify', max_length=100, verbose_name='Endpoint for Classify')),
                ('endpoint_classify_set', models.CharField(default='/api/v1/classify_set', max_length=100, verbose_name='Endpoint for Classify Set')),
                ('data_sharing_is_enabled', models.BooleanField(default=True, verbose_name='Data Sharing - Is Enabled?')),
                ('data_sharing_mode', models.PositiveSmallIntegerField(choices=[(0, 'On Update'), (1, 'On Finished')], default=0, verbose_name='Data Sharing - Mode')),
                ('classification_request', models.BooleanField(default=True, verbose_name='Request Classification Service')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Last Updated Timestamp')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadata')),
                ('unit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_node', to='units.unit', verbose_name='Unit')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_node', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Network Node',
                'verbose_name_plural': 'Network Nodes',
            },
        ),
    ]
