# Generated by Django 3.1.5 on 2021-03-15 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_currentclassifier_network_voting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalclassifier',
            name='classifier_url',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='endpoint_classify',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='endpoint_classify_set',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='id',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='name',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='node_url',
        ),
        migrations.AddField(
            model_name='externalclassifier',
            name='endpoint_classify',
            field=models.CharField(default='/api/v1/classify', max_length=100, verbose_name='Endpoint for Classify'),
        ),
        migrations.AddField(
            model_name='externalclassifier',
            name='endpoint_classify_set',
            field=models.CharField(default='/api/v1/classify_set', max_length=100, verbose_name='Endpoint for Classify Set'),
        ),
        migrations.AddField(
            model_name='externalclassifier',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Updated Timestamp'),
        ),
        migrations.AddField(
            model_name='externalclassifier',
            name='service_url',
            field=models.URLField(default='http://localhost', verbose_name='Service URL'),
        ),
        migrations.AddField(
            model_name='networknode',
            name='externalclassifier_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.externalclassifier'),
            preserve_default=False,
        ),
    ]
