# Generated by Django 3.1.5 on 2021-03-20 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_refactor_externalclassifier_networknode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalclassifier',
            options={'verbose_name': 'External Classifier', 'verbose_name_plural': 'External Classifiers'},
        ),
    ]
