# Generated by Django 3.1.5 on 2021-03-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_externalclassifier_fix_endpoint_classify_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'Other'), (1, 'Classify'), (2, 'Share Data')], default=0, verbose_name='Action')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Status Code')),
                ('message', models.CharField(max_length=512, verbose_name='Error Message')),
                ('external_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors_log', to='base.externalclassifier')),
            ],
            options={
                'verbose_name': 'Network Error Log',
                'verbose_name_plural': 'Network Error Logs',
            },
        ),
    ]
