# Generated by Django 3.1.5 on 2021-03-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_networkerrorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalclassifier',
            name='remote_user',
            field=models.CharField(blank=True, help_text='Username in the External Service for making requests', max_length=50, null=True, verbose_name='Remote User'),
        ),
        migrations.AddField(
            model_name='externalclassifier',
            name='remote_user_token',
            field=models.CharField(blank=True, help_text='Token for authenticating in the External Service', max_length=250, null=True, verbose_name='Remote User Token'),
        ),
    ]
