# Generated by Django 3.1.5 on 2021-03-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_externalclassifier_remote_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalclassifier',
            name='metrics',
            field=models.CharField(blank=True, help_text="Metrics (sklearn) to be evaluated with the external classifier, separated by comma and space, i.e. 'accuracy_score, precision_score, recall_score, fowlkes_mallows_score'", max_length=200, null=True, verbose_name='Metrics'),
        ),
    ]
