# Generated by Django 3.1.5 on 2021-04-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_externalclassifier_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentclassifier',
            name='breaking_ties_policy',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Prefer Local Vote'), (1, 'Prefer Highest Score')], default=0, help_text='Only applicable for Majority voting policy.', verbose_name='Breaking Ties Policy'),
        ),
        migrations.AlterField(
            model_name='currentclassifier',
            name='network_voting',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Network Voting'), (1, 'Majority'), (2, 'Minimum of Positives'), (3, 'Minimum of Negatives')], default=0, verbose_name='Network Voting Policy'),
        ),
    ]
