# Generated by Django 3.1.5 on 2021-04-08 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_currentclassifier_breaking_ties_policy_network_voting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalclassifier',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Last Updated Timestamp'),
            preserve_default=False,
        ),
    ]
