# Generated by Django 3.1.5 on 2021-04-20 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervised_learning', '0009_hgbtreeimputer'),
        ('base', '0015_externalclassifier_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentclassifier',
            name='classifier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_classifier', to='supervised_learning.supervisedlearningtechnique', verbose_name='Internal Classifier'),
        ),
        migrations.AlterField(
            model_name='currentclassifier',
            name='external',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_classifier', to='base.externalclassifier', verbose_name='External Classifier'),
        ),
    ]
